apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cortecerto
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:troque-esta-senha@postgres-hml:5432/dbcortes_homolog?schema=public"
  ADMIN_API_KEY: "troque-por-uma-chave-forte"
