apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cortecerto
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:change-me@db-host:5432/dbcortes?schema=public"
  ADMIN_API_KEY: "troque-por-uma-chave-forte"
