const express = require('express')
const agendamentosRoutes = require('../modules/agendamentos/routes')
const authRoutes = require('../modules/auth/routes')
const barbeariasRoutes = require('../modules/barbearias/routes')
const clientesRoutes = require('../modules/clientes/routes')
const servicosRoutes = require('../modules/servicos/routes')
const publicoRoutes = require('../modules/publico/routes')
const dashboardRoutes = require('../modules/dashboard/routes')
const billingRoutes = require('../modules/billing/routes')
const requireAdminApiKey = require('../http/adminAuth')
const requireActiveSubscription = require('../http/subscriptionGuard')

const router = express.Router()

router.use('/public', publicoRoutes)
router.use('/auth', authRoutes)
router.use('/billing', billingRoutes)
router.use('/Agendamento', requireAdminApiKey, requireActiveSubscription, agendamentosRoutes)
router.use('/Barbearia', requireAdminApiKey, barbeariasRoutes)
router.use('/Cliente', requireAdminApiKey, requireActiveSubscription, clientesRoutes)
router.use('/Servico', requireAdminApiKey, requireActiveSubscription, servicosRoutes)
router.use('/agendamentos', requireAdminApiKey, requireActiveSubscription, agendamentosRoutes)
router.use('/barbearias', requireAdminApiKey, barbeariasRoutes)
router.use('/clientes', requireAdminApiKey, requireActiveSubscription, clientesRoutes)
router.use('/servicos', requireAdminApiKey, requireActiveSubscription, servicosRoutes)
router.use('/dashboard', requireAdminApiKey, requireActiveSubscription, dashboardRoutes)

module.exports = router
